-- H2 Test Database Schema (MySQL Mode)

-- 1. 系统用户表
CREATE TABLE IF NOT EXISTS sys_user (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(64) NOT NULL,
    password_hash   VARCHAR(255) NOT NULL,
    nickname        VARCHAR(64),
    email           VARCHAR(128),
    phone           VARCHAR(20),
    avatar_url      VARCHAR(512),
    role            VARCHAR(32) NOT NULL DEFAULT 'USER',
    status          TINYINT NOT NULL DEFAULT 1,
    last_login_at   DATETIME,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 2. LLM 系统级厂商配置表
CREATE TABLE IF NOT EXISTS llm_system_provider (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_type   VARCHAR(32) NOT NULL,
    provider_name   VARCHAR(64) NOT NULL,
    icon_url        VARCHAR(512),
    icon_object_key VARCHAR(256),
    api_base_url    VARCHAR(512) NOT NULL,
    default_protocol VARCHAR(32) NOT NULL DEFAULT 'openai',
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    priority        INT NOT NULL DEFAULT 50,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 2.1 厂商模型能力目录表
CREATE TABLE IF NOT EXISTS llm_provider_model (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id     BIGINT NOT NULL,
    model_name      VARCHAR(128) NOT NULL,
    display_name    VARCHAR(64),
    capability      VARCHAR(32) NOT NULL,
    protocol        VARCHAR(32),
    api_base_url    VARCHAR(512),
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS llm_provider_model_sync_job (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id     BIGINT NOT NULL,
    sync_source     VARCHAR(32) NOT NULL,
    status          VARCHAR(16) NOT NULL,
    added_count     INT NOT NULL DEFAULT 0,
    updated_count   INT NOT NULL DEFAULT 0,
    stale_count     INT NOT NULL DEFAULT 0,
    error_message   VARCHAR(512),
    started_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at     DATETIME
);

CREATE TABLE IF NOT EXISTS llm_provider_model_sync_candidate (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id                      BIGINT NOT NULL,
    provider_id                 BIGINT NOT NULL,
    sync_source                 VARCHAR(32) NOT NULL,
    external_model_id           VARCHAR(192) NOT NULL,
    model_name                  VARCHAR(128) NOT NULL,
    display_name                VARCHAR(64),
    inferred_capability         VARCHAR(32) NOT NULL,
    inferred_protocol           VARCHAR(32),
    inferred_api_base_url       VARCHAR(512),
    context_window              INT,
    max_output_tokens           INT,
    model_release_date          DATE,
    input_modalities            VARCHAR(1024),
    output_modalities           VARCHAR(1024),
    raw_metadata                CLOB,
    review_status               VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    matched_provider_model_id   BIGINT,
    last_seen_at                DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at                  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 2.2 系统预设表
CREATE TABLE IF NOT EXISTS llm_system_preset (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id     BIGINT NOT NULL,
    model_name      VARCHAR(128) NOT NULL,
    display_name    VARCHAR(64),
    capability      VARCHAR(32) NOT NULL,
    provider_type   VARCHAR(32),
    protocol        VARCHAR(32),
    api_base_url    VARCHAR(512),
    api_key         VARCHAR(512) NOT NULL,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    is_default      BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 3. 用户级 LLM 配置表
CREATE TABLE IF NOT EXISTS llm_user_config (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT NOT NULL,
    provider_id         BIGINT NOT NULL,
    provider_type       VARCHAR(32) NOT NULL,
    api_key             VARCHAR(512) NOT NULL,
    api_base_url        VARCHAR(512),
    protocol            VARCHAR(32),
    model_name          VARCHAR(128) NOT NULL,
    capability          VARCHAR(32) NOT NULL DEFAULT 'CHAT',
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    is_default          BOOLEAN NOT NULL DEFAULT FALSE,
    is_system_preset    BOOLEAN NOT NULL DEFAULT FALSE,
    created_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 4. 对话表
CREATE TABLE IF NOT EXISTS dataset (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL,
    name            VARCHAR(128) NOT NULL,
    description     VARCHAR(512),
    status          VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    is_deleted      BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_seq     BIGINT NOT NULL DEFAULT 0,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_dataset_user_name_seq ON dataset(user_id, name, deleted_seq);
CREATE INDEX IF NOT EXISTS idx_dataset_user_updated ON dataset(user_id, updated_at);

-- 5. 对话表
CREATE TABLE IF NOT EXISTS chat_conversation (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL,
    dataset_id      BIGINT NOT NULL,
    last_config_id  BIGINT,
    last_model_name VARCHAR(128),
    title           VARCHAR(255),
    is_pinned       BOOLEAN DEFAULT FALSE,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 6. 对话消息表（一行一轮：query + answer 同行）
CREATE TABLE IF NOT EXISTS chat_message (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id     BIGINT NOT NULL,
    -- 轮次幂等键（前端每轮稳定 UUID）；列结构归 Python migration 0023，本地/测试 schema 与之保持一致。
    turn_id             VARCHAR(64),
    config_id           BIGINT,
    model_name          VARCHAR(128),
    `query`             TEXT,
    answer              TEXT,
    -- 生产 MySQL 为 JSON 列；H2 测试库降级为 VARCHAR 存 JSON 文本，与 MyBatis JacksonTypeHandler 行为一致（见 dataset_parse_config）。
    `references`        VARCHAR,
    request_id          VARCHAR(64),
    status              VARCHAR(16) NOT NULL DEFAULT 'GENERATING',
    error_code          VARCHAR(64),
    error_message       VARCHAR(512),
    created_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 7. LLM 调用用量日志表
CREATE TABLE IF NOT EXISTS llm_usage_log (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT NOT NULL,
    config_id           BIGINT,
    provider_type       VARCHAR(32) NOT NULL,
    model_name          VARCHAR(128) NOT NULL,
    stage               VARCHAR(16) NOT NULL,
    operation           VARCHAR(16) NOT NULL,
    prompt_tokens       INT NOT NULL,
    completion_tokens   INT NOT NULL,
    total_tokens        INT NOT NULL,
    latency_ms          INT,
    status              VARCHAR(16) NOT NULL,
    error_message       VARCHAR(512),
    created_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_sys_user_username ON sys_user(username);
CREATE INDEX IF NOT EXISTS idx_sys_user_email ON sys_user(email);
CREATE INDEX IF NOT EXISTS idx_llm_user_config_user_id ON llm_user_config(user_id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_user_provider_model_capability ON llm_user_config(user_id, provider_id, model_name, capability, is_system_preset);
CREATE UNIQUE INDEX IF NOT EXISTS uk_provider_model_cap ON llm_provider_model(provider_id, model_name, capability);
CREATE INDEX IF NOT EXISTS idx_sync_job_provider ON llm_provider_model_sync_job(provider_id, started_at);
CREATE INDEX IF NOT EXISTS idx_sync_candidate_provider_status ON llm_provider_model_sync_candidate(provider_id, review_status);
CREATE UNIQUE INDEX IF NOT EXISTS uk_sync_candidate_provider_source_model_cap ON llm_provider_model_sync_candidate(provider_id, sync_source, model_name, inferred_capability);
CREATE UNIQUE INDEX IF NOT EXISTS uk_preset_provider_model_cap ON llm_system_preset(provider_id, model_name, capability);
CREATE INDEX IF NOT EXISTS idx_chat_conversation_user_pinned_updated ON chat_conversation(user_id, is_pinned, updated_at);
CREATE INDEX IF NOT EXISTS idx_chat_conversation_dataset_updated ON chat_conversation(dataset_id, updated_at);
CREATE INDEX IF NOT EXISTS idx_chat_message_conversation_id ON chat_message(conversation_id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_chat_message_turn_id ON chat_message(turn_id);
CREATE INDEX IF NOT EXISTS idx_llm_usage_log_user_id ON llm_usage_log(user_id);

-- 8. 文档文件原文件表
CREATE TABLE IF NOT EXISTS document_original_file (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_id                 BIGINT NOT NULL,
    user_id                    BIGINT NOT NULL,
    original_filename          VARCHAR(255) NOT NULL,
    file_suffix                VARCHAR(32) NOT NULL,
    file_size                  BIGINT NOT NULL,
    content_type               VARCHAR(128),
    bucket_name                VARCHAR(64) NOT NULL DEFAULT 'rag-raw',
    object_key                 VARCHAR(512),
    file_url                   VARCHAR(1024),
    upload_status              VARCHAR(20) NOT NULL DEFAULT 'uploading',
    is_upload_success          BOOLEAN NOT NULL DEFAULT FALSE,
    failure_reason             VARCHAR(512),
    is_deleted                 BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_seq                BIGINT NOT NULL DEFAULT 0,
    created_at                 DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                 DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_dof_name_suffix_seq
    ON document_original_file(dataset_id, user_id, original_filename, file_suffix, deleted_seq);
CREATE INDEX IF NOT EXISTS idx_document_original_dataset_created ON document_original_file(dataset_id, created_at);
CREATE INDEX IF NOT EXISTS idx_document_original_user_created ON document_original_file(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_document_original_upload_status ON document_original_file(upload_status, updated_at);

-- 9. 文件解析聚合表
CREATE TABLE IF NOT EXISTS document_parse_file (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_original_file_id  BIGINT NOT NULL,
    dataset_id                 BIGINT NOT NULL,
    user_id                    BIGINT NOT NULL,
    latest_parse_task_id       VARCHAR(36),
    original_filename          VARCHAR(255) NOT NULL,
    parse_count                INT NOT NULL DEFAULT 0,
    created_at                 DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                 DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_parse_file_original_file ON document_parse_file(document_original_file_id);
CREATE INDEX IF NOT EXISTS idx_parse_file_dataset_user ON document_parse_file(dataset_id, user_id, updated_at);
CREATE INDEX IF NOT EXISTS idx_parse_file_latest_task ON document_parse_file(latest_parse_task_id);

-- 10. 文件解析日志表
CREATE TABLE IF NOT EXISTS document_parsed_log (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id                    VARCHAR(36) NOT NULL,
    document_original_file_id  BIGINT NOT NULL,
    document_parse_file_id     BIGINT,
    trigger_mode               VARCHAR(20) NOT NULL,
    parsed_filename            VARCHAR(255),
    parsed_bucket_name         VARCHAR(64),
    parsed_object_key          VARCHAR(512),
    parsed_file_url            VARCHAR(1024),
    parsed_at                  DATETIME,
    parse_started_at           DATETIME,
    parse_finished_at          DATETIME,
    parse_duration_ms          BIGINT,
    retry_of_task_id           VARCHAR(36),
    created_at                 DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                 DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_parsed_log_task_id ON document_parsed_log(task_id);
CREATE INDEX IF NOT EXISTS idx_parsed_log_original_file
    ON document_parsed_log(document_original_file_id, updated_at);
CREATE INDEX IF NOT EXISTS idx_parsed_log_parse_file
    ON document_parsed_log(document_parse_file_id, updated_at);
CREATE INDEX IF NOT EXISTS idx_parsed_log_retry_of ON document_parsed_log(retry_of_task_id);

-- 11. 文件后处理流水线表（含稀疏向量阶段）；Python 写入并推进终态，Java 只读
CREATE TABLE IF NOT EXISTS document_parse_pipeline (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_parsed_log_id     BIGINT NOT NULL,
    task_id                    VARCHAR(36) NOT NULL,
    document_original_file_id  BIGINT NOT NULL,
    document_parse_file_id     BIGINT,
    pipeline_status            VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    failed_stage               VARCHAR(20),
    recover_from_stage         VARCHAR(20),
    failure_reason             VARCHAR(512),
    superseded_by_task_id      VARCHAR(36),
    started_at                 DATETIME,
    finished_at                DATETIME,
    created_at                 DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                 DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_parse_pipeline_parsed_log ON document_parse_pipeline(document_parsed_log_id);
CREATE INDEX IF NOT EXISTS idx_parse_pipeline_task_id ON document_parse_pipeline(task_id);
CREATE INDEX IF NOT EXISTS idx_parse_pipeline_status ON document_parse_pipeline(pipeline_status, updated_at);
CREATE INDEX IF NOT EXISTS idx_parse_pipeline_superseded ON document_parse_pipeline(superseded_by_task_id);

-- 12. 文档 Chunk 真值记录表（Python 写，Java 只读）
CREATE TABLE IF NOT EXISTS kb_document_chunk (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chunk_id                    VARCHAR(128) NOT NULL,
    doc_id                      BIGINT NOT NULL,
    set_id                      BIGINT NOT NULL,
    user_id                     BIGINT NOT NULL,
    bucket_id                   INT,
    content                     TEXT NOT NULL,
    content_hash                VARCHAR(64) NOT NULL,
    chunk_type                  VARCHAR(32) NOT NULL DEFAULT 'text',
    start_line                  INT,
    end_line                    INT,
    chunk_index                 INT,
    dense_vector_status         VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    dense_vector_model          VARCHAR(128),
    sparse_vector_status        VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    sparse_vector_model         VARCHAR(128),
    es_status                   VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    lifecycle_status            VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    create_time                 DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time                 DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_chunk_id ON kb_document_chunk(chunk_id);
CREATE INDEX IF NOT EXISTS idx_user_set ON kb_document_chunk(user_id, set_id);
CREATE INDEX IF NOT EXISTS idx_doc_dense_status ON kb_document_chunk(doc_id, dense_vector_status);
CREATE INDEX IF NOT EXISTS idx_doc_sparse_status ON kb_document_chunk(doc_id, sparse_vector_status);
CREATE INDEX IF NOT EXISTS idx_doc_es_status ON kb_document_chunk(doc_id, es_status);
CREATE INDEX IF NOT EXISTS idx_doc_lifecycle_status ON kb_document_chunk(doc_id, lifecycle_status);
CREATE INDEX IF NOT EXISTS idx_lifecycle_update_time ON kb_document_chunk(lifecycle_status, update_time);

-- 13. 博客文章表
CREATE TABLE IF NOT EXISTS blog_post (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title               VARCHAR(255) NOT NULL,
    slug                VARCHAR(255) NOT NULL,
    summary             VARCHAR(1000),
    content_object_key  VARCHAR(512),
    cover_asset_id      BIGINT,
    status              VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    published_at        DATETIME,
    created_by          BIGINT NOT NULL,
    is_deleted          BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_seq         BIGINT NOT NULL DEFAULT 0,
    created_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_blog_post_slug_seq ON blog_post(slug, deleted_seq);
CREATE INDEX IF NOT EXISTS idx_blog_post_public_list ON blog_post(status, published_at, id);
CREATE INDEX IF NOT EXISTS idx_blog_post_admin_list ON blog_post(is_deleted, updated_at, id);

-- 13. 博客文章资源表
CREATE TABLE IF NOT EXISTS blog_asset (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id             BIGINT NOT NULL,
    asset_type          VARCHAR(20) NOT NULL,
    original_filename   VARCHAR(255) NOT NULL,
    content_type        VARCHAR(128) NOT NULL,
    file_size           BIGINT NOT NULL,
    object_key          VARCHAR(512) NOT NULL,
    public_url          VARCHAR(1024) NOT NULL,
    created_by          BIGINT NOT NULL,
    is_deleted          BOOLEAN NOT NULL DEFAULT FALSE,
    created_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_blog_asset_object_key ON blog_asset(object_key);
CREATE INDEX IF NOT EXISTS idx_blog_asset_post_type ON blog_asset(post_id, asset_type, is_deleted, created_at);

-- 14. Anonymous user feedback table
CREATE TABLE IF NOT EXISTS user_feedback (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type                  VARCHAR(32) NOT NULL DEFAULT 'OTHER',
    title                 VARCHAR(128) NOT NULL,
    content               TEXT NOT NULL,
    attachment_object_key VARCHAR(512),
    status                VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    priority              TINYINT NOT NULL DEFAULT 3,
    admin_id              BIGINT,
    admin_reply           TEXT,
    processed_at          DATETIME,
    created_at            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_feedback_created ON user_feedback(created_at);
CREATE INDEX IF NOT EXISTS idx_feedback_status_priority ON user_feedback(status, priority, created_at);
CREATE INDEX IF NOT EXISTS idx_feedback_type_created ON user_feedback(type, created_at);

-- 15. Dataset parse/recall config table (cross-end shared with Python; aligned to Python migration 0017/0030)
CREATE TABLE IF NOT EXISTS dataset_parse_config (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT NOT NULL,
    dataset_id          BIGINT NOT NULL,
    sparse_embedding_config_id BIGINT,
    dense_embedding_config_id  BIGINT,
    -- 生产 MySQL 为 JSON 列；H2 测试库降级为 VARCHAR 存 JSON 文本：H2 的 JSON 列经 JDBC setString
    -- 会被当作「一个 JSON 字符串字面量」而非 JSON 文档，与 MyBatis JacksonTypeHandler 不兼容，
    -- 故测试库用 VARCHAR（TypeHandler setString/getString JSON 文本，行为与生产一致）。
    chunking_config     VARCHAR NOT NULL,
    enhancement_config  VARCHAR NOT NULL,
    pdf_config          VARCHAR NOT NULL,
    recall_config       VARCHAR NOT NULL,
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    created_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_user_dataset ON dataset_parse_config(user_id, dataset_id);
CREATE INDEX IF NOT EXISTS idx_dataset_parse_sparse_config ON dataset_parse_config(sparse_embedding_config_id);
CREATE INDEX IF NOT EXISTS idx_dataset_parse_dense_config ON dataset_parse_config(dense_embedding_config_id);
CREATE INDEX IF NOT EXISTS idx_dataset_parse_config_dataset ON dataset_parse_config(dataset_id);
