-- H2 Test Database Schema (MySQL Mode)

-- 1. 系统用户表
CREATE TABLE IF NOT EXISTS sys_user (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(64) NOT NULL,
    password_hash   VARCHAR(255) NOT NULL,
    nickname        VARCHAR(64),
    email           VARCHAR(128),
    phone           VARCHAR(20),
    avatar_url      VARCHAR(512),
    role            VARCHAR(32) NOT NULL DEFAULT 'USER',
    status          TINYINT NOT NULL DEFAULT 1,
    last_login_at   DATETIME,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted      BOOLEAN DEFAULT FALSE
);

-- 2. LLM 系统级厂商配置表
CREATE TABLE IF NOT EXISTS llm_system_provider (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_type   VARCHAR(32) NOT NULL,
    provider_name   VARCHAR(64) NOT NULL,
    api_base_url    VARCHAR(512) NOT NULL,
    supported_models JSON,
    config_schema   JSON,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    priority        INT NOT NULL DEFAULT 50,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 3. 用户级 LLM 配置表
CREATE TABLE IF NOT EXISTS llm_user_config (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT NOT NULL,
    provider_id         BIGINT NOT NULL,
    provider_type       VARCHAR(32) NOT NULL,
    provider_name       VARCHAR(64) NOT NULL,
    config_name         VARCHAR(64) NOT NULL,
    api_key             VARCHAR(512) NOT NULL,
    custom_api_base_url VARCHAR(512),
    model_name          VARCHAR(128) NOT NULL,
    priority            INT NOT NULL DEFAULT 50,
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    is_default          BOOLEAN NOT NULL DEFAULT FALSE,
    timeout_ms          INT DEFAULT 60000,
    max_retries         INT DEFAULT 3,
    stream_enabled      BOOLEAN DEFAULT TRUE,
    capabilities        JSON,
    extra_config        JSON,
    created_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 4. 对话表
CREATE TABLE IF NOT EXISTS chat_conversation (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL,
    last_config_id  BIGINT,
    last_model_name VARCHAR(128),
    title           VARCHAR(255),
    is_pinned       BOOLEAN DEFAULT FALSE,
    is_deleted      BOOLEAN DEFAULT FALSE,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 5. 对话消息表
CREATE TABLE IF NOT EXISTS chat_message (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id     BIGINT NOT NULL,
    config_id           BIGINT,
    model_name          VARCHAR(128),
    role                VARCHAR(16) NOT NULL,
    content             TEXT NOT NULL,
    token_count         INT DEFAULT 0,
    created_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 6. LLM 调用用量日志表
CREATE TABLE IF NOT EXISTS llm_usage_log (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT NOT NULL,
    config_id           BIGINT NOT NULL,
    provider_type       VARCHAR(32) NOT NULL,
    model_name          VARCHAR(128) NOT NULL,
    prompt_tokens       INT NOT NULL,
    completion_tokens   INT NOT NULL,
    total_tokens        INT NOT NULL,
    latency_ms          INT,
    status              VARCHAR(16) NOT NULL,
    error_message       VARCHAR(512),
    fallback_config_id  BIGINT,
    conversation_id     BIGINT,
    created_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_sys_user_username ON sys_user(username);
CREATE INDEX IF NOT EXISTS idx_sys_user_email ON sys_user(email);
CREATE INDEX IF NOT EXISTS idx_llm_user_config_user_id ON llm_user_config(user_id);
CREATE INDEX IF NOT EXISTS idx_chat_conversation_user_id ON chat_conversation(user_id);
CREATE INDEX IF NOT EXISTS idx_chat_message_conversation_id ON chat_message(conversation_id);
CREATE INDEX IF NOT EXISTS idx_llm_usage_log_user_id ON llm_usage_log(user_id);
