-- H2 Test Database Schema (MySQL Mode)

-- 1. 系统用户表
CREATE TABLE IF NOT EXISTS sys_user (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(64) NOT NULL,
    password_hash   VARCHAR(255) NOT NULL,
    nickname        VARCHAR(64),
    email           VARCHAR(128),
    phone           VARCHAR(20),
    avatar_url      VARCHAR(512),
    role            VARCHAR(32) NOT NULL DEFAULT 'USER',
    status          TINYINT NOT NULL DEFAULT 1,
    last_login_at   DATETIME,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 2. LLM 系统级厂商配置表
CREATE TABLE IF NOT EXISTS llm_system_provider (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_type   VARCHAR(32) NOT NULL,
    provider_name   VARCHAR(64) NOT NULL,
    api_base_url    VARCHAR(512) NOT NULL,
    supported_models JSON,
    config_schema   JSON,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    priority        INT NOT NULL DEFAULT 50,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 3. 用户级 LLM 配置表
CREATE TABLE IF NOT EXISTS llm_user_config (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT NOT NULL,
    provider_id         BIGINT NOT NULL,
    provider_type       VARCHAR(32) NOT NULL,
    provider_name       VARCHAR(64) NOT NULL,
    config_name         VARCHAR(64) NOT NULL,
    api_key             VARCHAR(512) NOT NULL,
    custom_api_base_url VARCHAR(512),
    model_name          VARCHAR(128) NOT NULL,
    priority            INT NOT NULL DEFAULT 50,
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    is_default          BOOLEAN NOT NULL DEFAULT FALSE,
    timeout_ms          INT DEFAULT 60000,
    max_retries         INT DEFAULT 3,
    stream_enabled      BOOLEAN DEFAULT TRUE,
    capabilities        JSON,
    extra_config        JSON,
    created_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 4. 对话表
CREATE TABLE IF NOT EXISTS dataset (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL,
    name            VARCHAR(128) NOT NULL,
    description     VARCHAR(512),
    status          VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_dataset_user_name ON dataset(user_id, name);
CREATE INDEX IF NOT EXISTS idx_dataset_user_updated ON dataset(user_id, updated_at);

-- 5. 对话表
CREATE TABLE IF NOT EXISTS chat_conversation (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL,
    dataset_id      BIGINT NOT NULL,
    last_config_id  BIGINT,
    last_model_name VARCHAR(128),
    title           VARCHAR(255),
    is_pinned       BOOLEAN DEFAULT FALSE,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 6. 对话消息表
CREATE TABLE IF NOT EXISTS chat_message (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id     BIGINT NOT NULL,
    config_id           BIGINT,
    model_name          VARCHAR(128),
    role                VARCHAR(16) NOT NULL,
    content             TEXT NOT NULL,
    token_count         INT DEFAULT 0,
    created_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 7. LLM 调用用量日志表
CREATE TABLE IF NOT EXISTS llm_usage_log (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT NOT NULL,
    config_id           BIGINT NOT NULL,
    provider_type       VARCHAR(32) NOT NULL,
    model_name          VARCHAR(128) NOT NULL,
    prompt_tokens       INT NOT NULL,
    completion_tokens   INT NOT NULL,
    total_tokens        INT NOT NULL,
    latency_ms          INT,
    status              VARCHAR(16) NOT NULL,
    error_message       VARCHAR(512),
    fallback_config_id  BIGINT,
    conversation_id     BIGINT,
    created_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_sys_user_username ON sys_user(username);
CREATE INDEX IF NOT EXISTS idx_sys_user_email ON sys_user(email);
CREATE INDEX IF NOT EXISTS idx_llm_user_config_user_id ON llm_user_config(user_id);
CREATE INDEX IF NOT EXISTS idx_chat_conversation_user_pinned_updated ON chat_conversation(user_id, is_pinned, updated_at);
CREATE INDEX IF NOT EXISTS idx_chat_conversation_dataset_updated ON chat_conversation(dataset_id, updated_at);
CREATE INDEX IF NOT EXISTS idx_chat_message_conversation_id ON chat_message(conversation_id);
CREATE INDEX IF NOT EXISTS idx_llm_usage_log_user_id ON llm_usage_log(user_id);

-- 8. 知识文件原文件表
CREATE TABLE IF NOT EXISTS document_original_file (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_id                 BIGINT NOT NULL,
    user_id                    BIGINT NOT NULL,
    original_filename          VARCHAR(255) NOT NULL,
    file_suffix                VARCHAR(32) NOT NULL,
    file_size                  BIGINT NOT NULL,
    content_type               VARCHAR(128),
    bucket_name                VARCHAR(64) NOT NULL DEFAULT 'rag-raw',
    object_key                 VARCHAR(512),
    file_url                   VARCHAR(1024),
    upload_status              VARCHAR(20) NOT NULL DEFAULT 'uploading',
    is_upload_success          BOOLEAN NOT NULL DEFAULT FALSE,
    parse_notice_status        VARCHAR(24) NOT NULL DEFAULT 'pending',
    parse_task_id              VARCHAR(36) NOT NULL,
    parse_task_record_id       BIGINT,
    failure_reason             VARCHAR(512),
    parse_notice_retry_count   INT NOT NULL DEFAULT 0,
    last_parse_notice_at       DATETIME,
    created_at                 DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                 DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_document_original_parse_task_id ON document_original_file(parse_task_id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_document_original_dataset_filename
    ON document_original_file(dataset_id, original_filename);
CREATE INDEX IF NOT EXISTS idx_document_original_dataset_created ON document_original_file(dataset_id, created_at);
CREATE INDEX IF NOT EXISTS idx_document_original_user_created ON document_original_file(user_id, created_at);

-- 9. 解析结果文件表
CREATE TABLE IF NOT EXISTS document_parsed_file (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_original_file_id  BIGINT NOT NULL,
    dataset_id                 BIGINT NOT NULL,
    user_id                    BIGINT NOT NULL,
    parse_task_id              VARCHAR(36) NOT NULL,
    original_filename          VARCHAR(255) NOT NULL,
    parse_status               VARCHAR(16) NOT NULL DEFAULT 'pending',
    is_parse_success           BOOLEAN NOT NULL DEFAULT FALSE,
    parsed_filename            VARCHAR(255),
    parsed_bucket_name         VARCHAR(64),
    parsed_object_key          VARCHAR(512),
    parsed_file_url            VARCHAR(1024),
    parsed_storage_path        VARCHAR(1024),
    parse_result               CLOB,
    failure_reason             VARCHAR(512),
    parsed_at                  DATETIME,
    last_result_at             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at                 DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                 DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_document_parsed_original_file
    ON document_parsed_file(document_original_file_id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_document_parsed_task_id
    ON document_parsed_file(parse_task_id);
CREATE INDEX IF NOT EXISTS idx_document_parsed_dataset_status
    ON document_parsed_file(dataset_id, parse_status, updated_at);
CREATE INDEX IF NOT EXISTS idx_document_parsed_user_status
    ON document_parsed_file(user_id, parse_status, updated_at);

-- 10. 知识文件上传配置表
CREATE TABLE IF NOT EXISTS knowledge_file_config (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    max_size_bytes      BIGINT NOT NULL,
    allowed_suffixes    VARCHAR(1024) NOT NULL,
    updated_by          BIGINT NOT NULL,
    created_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
